### PR TITLE
Fixed player damage check

### LINKED ISSUE #114: PVP In/ Out of Town
Damage is being dealt to players inside of a town with PVP disabled, if the attacker is outside of the town.

### PR DESCRIPTION
**Pull request by codestripper**
Fixes #114

### CODE REVIEW

File: src/main/java/com/atherys/towns/facade/TownFacade.java [hunk 1]
```diff
@@ -535,11 +535,20 @@ public Text renderTowns(Collection<Town> towns) {
...
-    public void onPlayerDamage(DamageEntityEvent event, Player player) {
-        plotService.getPlotByLocation(player.getLocation()).ifPresent(plot -> {
-            Town townAtPlot = plot.getTown();
-            event.setCancelled(!townAtPlot.isPvpEnabled());
-        });
+    public void onPlayerDamage(DamageEntityEvent event, Player attacker, Player target) {
+        Optional<Plot> attackerPlot = plotService.getPlotByLocation(attacker.getLocation());
+        Optional<Plot> targetPlot = plotService.getPlotByLocation(target.getLocation());
+        //If the attacker and the target are not in plots, then return.
+        if (!(attackerPlot.isPresent() || targetPlot.isPresent())) {
```
Comment (svenwiltink) [inline src/main/java/com/atherys/towns/facade/TownFacade.java:542]: If(!attackersPlot.isPresent() && !targetPlot.isPresent()) does the same but might be more readable

Comment (codestripper) [reply src/main/java/com/atherys/towns/facade/TownFacade.java]: This has been changed.
